import { css } from 'linaria'
import type { NextPage } from 'next'
import Head from 'next/head'

const container = css`
  width: 100%;
  max-width: 800px;
  display: flex;
  justify-content: center;
  padding: 32px;
  margin: 0 auto;
  flex-direction: column;
`

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={container}>
        <h1>Ahoy - Solana Summer</h1>
        <p>todo</p>
      </div>
    </>
  )
}

export default Home
