[features]
seeds = false
[programs.localnet]
ahoy_grants = "Aam6DmZoo1qeJstSrmspbGgWh4E6WjBzWEyUFaoFjTQh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# spl_token_faucet (https://github.com/credix-finance/spl-token-faucet) is used
# to be able to simulate USDC when testing.
[[test.genesis]]
address = "4sN8PnN2ki2W4TFXAfzR645FWs8nimmsYeNtxM8RBK6A"
program = "spl_token_faucet.so"
