/* eslint-disable */
/*
 * This file is auto-generated by env-ts
 * Do not edit
 */

if (process.env.NEXT_PUBLIC_HEAP_ANALYTICS_KEY == null) {
  throw new Error('missing process.env.NEXT_PUBLIC_HEAP_ANALYTICS_KEY in app')
}
if (process.env.NEXT_PUBLIC_HEAP_ENABLED == null) {
  throw new Error('missing process.env.NEXT_PUBLIC_HEAP_ENABLED in app')
}
if (process.env.NEXT_PUBLIC_PROGRAM_ID == null) {
  throw new Error('missing process.env.NEXT_PUBLIC_PROGRAM_ID in app')
}
if (process.env.NEXT_PUBLIC_SENTRY_DSN == null) {
  throw new Error('missing process.env.NEXT_PUBLIC_SENTRY_DSN in app')
}
if (process.env.NEXT_PUBLIC_SENTRY_ENABLED == null) {
  throw new Error('missing process.env.NEXT_PUBLIC_SENTRY_ENABLED in app')
}
if (process.env.NEXT_PUBLIC_SOLANA_CLUSTER == null) {
  throw new Error('missing process.env.NEXT_PUBLIC_SOLANA_CLUSTER in app')
}

export const NEXT_PUBLIC_HEAP_ANALYTICS_KEY = process.env.NEXT_PUBLIC_HEAP_ANALYTICS_KEY
export const NEXT_PUBLIC_HEAP_ENABLED = process.env.NEXT_PUBLIC_HEAP_ENABLED
export const NEXT_PUBLIC_PROGRAM_ID = process.env.NEXT_PUBLIC_PROGRAM_ID
export const NEXT_PUBLIC_SENTRY_DSN = process.env.NEXT_PUBLIC_SENTRY_DSN
export const NEXT_PUBLIC_SENTRY_ENABLED = process.env.NEXT_PUBLIC_SENTRY_ENABLED
export const NEXT_PUBLIC_SOLANA_CLUSTER = process.env.NEXT_PUBLIC_SOLANA_CLUSTER
